### ISSUE TITLE
Allow renaming of bags in configuration file

### ISSUE THREAD

**Issue by runfalk** [lorddusk/Bagginses#22] opened 2016-01-31 12:54 UTC
It would be useful to allow renaming of the bags in the configuration file, or add a custom description. That way it is easy to know which bag does what without requiring displaying all items in whitelist.

**Comment by AKTheKnight** [comment] 2016-04-21 12:58
This is a duplicate of #08

**Comment by AKTheKnight** [comment] 2016-04-21 19:52
This has been added in 29f5901537a6d2b773ed8ef3c1d719d9951c7719

**Closed** 2016-04-21 20:54 UTC
Labels: enhancement
